"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import { Navbar, NavbarBrand, NavbarContent, NavbarItem, Link, Button } from "@nextui-org/react";
import { NavbarMenuToggle, NavbarMenu, NavbarMenuItem } from "@nextui-org/react";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { ThemeSwitcher } from "../components/ThemeSwitcher";
import { Providers } from "./Providers";
import { Document } from "react-pdf";
import { Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, useDisclosure } from "@nextui-org/modal";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
	// I removed the 'export'
	title: "Jerome Almoguera Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	// const [darkMode, setDarkMode] = useState(false);

	const [visible, setVisible] = useState(false);

	const openModal = () => setVisible(true);
	const closeModal = () => setVisible(false);

	return (
		<html lang="en">
			<body>
				<Providers>
					<Navbar>
						<NavbarContent>
							<NavbarBrand>
								<a href="./">
									<h1 className="text-xl font-main uppercase dark:text-white">Jerome Almoguera</h1>
								</a>
							</NavbarBrand>
						</NavbarContent>

						<NavbarContent justify="end">
							<NavbarItem className="hidden lg:flex">
								<ThemeSwitcher /> {/* Dark mode button */}
							</NavbarItem>
							<NavbarItem>
								<Button color="warning" variant="flat" onClick={openModal}>
									Resume
								</Button>
								<Modal open={visible} onClose={closeModal} width="80%">
									<ModalHeader>
										<h2>My Resume</h2>
									</ModalHeader>
									<ModalBody>
										<iframe src="../public/resume.pdf" width="100%" height="500px" style={{ border: "none" }} title="Resume"></iframe>
									</ModalBody>
								</Modal>
							</NavbarItem>
						</NavbarContent>
					</Navbar>

					{children}
				</Providers>

				{/* <script src="../path/to/flowbite/dist/flowbite.min.js"></script> */}
			</body>
		</html>
	);
}
