"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import { Navbar, NavbarBrand, NavbarContent, NavbarItem, Link, Button } from "@nextui-org/react";
import { NavbarMenuToggle, NavbarMenu, NavbarMenuItem } from "@nextui-org/react";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { ThemeSwitcher } from "../components/ThemeSwitcher";
import { Providers } from "./Providers";
import { Document } from "react-pdf";
import { Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, useDisclosure } from "@nextui-org/modal";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
	// I removed the 'export'
	title: "Jerome Almoguera Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	// const [darkMode, setDarkMode] = useState(false);

	const [isMenuOpen, setIsMenuOpen] = React.useState(false);

	const menuItems = ["Profile", "Dashboard", "Activity", "Analytics", "System", "Deployments", "My Settings", "Team Settings", "Help & Feedback", "Log Out"];

	return (
		<html lang="en">
			<body>
				<Providers>
					<Navbar onMenuOpenChange={setIsMenuOpen}>
						<NavbarContent>
							<NavbarMenuToggle aria-label={isMenuOpen ? "Close menu" : "Open menu"} className="sm:hidden" />
							<NavbarBrand>
								<a href="./">
									<h1 className="text-xl font-main uppercase dark:text-white">Jerome Almoguera</h1>
								</a>
							</NavbarBrand>
						</NavbarContent>

						<NavbarContent justify="end">
							<NavbarItem className="hidden lg:flex">
								<ThemeSwitcher /> {/* Dark mode button */}
							</NavbarItem>
							<NavbarItem>
								<Button color="warning" variant="flat">
									Resume
								</Button>
							</NavbarItem>
						</NavbarContent>
						<NavbarMenu>
							{menuItems.map((item, index) => (
								<NavbarMenuItem key={`${item}-${index}`}>
									<Link color={index === 2 ? "primary" : index === menuItems.length - 1 ? "danger" : "foreground"} className="w-full" href="#" size="lg">
										{item}
									</Link>
								</NavbarMenuItem>
							))}
						</NavbarMenu>
					</Navbar>

					{children}
				</Providers>

				{/* <script src="../path/to/flowbite/dist/flowbite.min.js"></script> */}
			</body>
		</html>
	);
}
